version: '3'

services:
  database:
    container_name: mysql_backend
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cisco
      MYSQL_DATABASE: stuff
      MYSQL_USER: luis
      MYSQL_PASSWORD: cisco
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./my_sql_data:/var/lib/mysql

  digital_passport:
    image: pdpp/papalote_digital_passport:0
    container_name: digital_passport
    depends_on:
      - database
    ports:
      - "8080:80"
    stdin_open: true
    tty: true

  rally_demo:
    container_name: papalote_interactive
    image: pdpp/papalote_interactive_demo:http
    ports:
      - '80:80'
    stdin_open: true
    tty: true
    