version: '3'

services:
  database:
    container_name: mysql_backend
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cisco
      MYSQL_DATABASE: stuff
      MYSQL_USER: luis
      MYSQL_PASSWORD: cisco
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./my_sql_data:/var/lib/mysql

  web:
    image: papalote_digital_passport:1
    container_name: digital_passport
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true